Rework messages on failed umounts
If the update succeeded, but the unmount of one of the bind mounts failed,
it will be attempted a second time to unmount the mount point. The error
message however will appear on the first attempt, even if the second
attempt was successful.
In combination with [boo#1168389] this behaviour is unfortunate, because
this may lead to the assumption that the complete update failed, so this
commit reworks the messages to only indicate a hard error if the second
attempt also didn't succeed.

diff --git a/sbin/transactional-update.in b/sbin/transactional-update.in
--- a/sbin/transactional-update.in
+++ b/sbin/transactional-update.in
@@ -314,16 +314,18 @@ teardown() {
 	fi
 	umount -R ${SNAPSHOT_DIR}/$directory
 	if [ $? -ne 0 ]; then
-	    log_error "ERROR: umount of $directory failed!"
-	    fuser -v ${SNAPSHOT_DIR}/$directory >> ${LOGFILE}
-	    lsof ${SNAPSHOT_DIR}/$directory >> ${LOGFILE}
-            # Try again after some time
-            sleep 30
-            umount -R ${SNAPSHOT_DIR}/$directory
-            if [ $? -ne 0 ]; then
-                log_error "ERROR 2nd try: umount of $directory failed!"
-	        EXITCODE=1;
-            fi
+	    log_error "Warning: First attempt to umount $directory failed!"
+	    # Try again after some time
+	    sleep 30
+	    umount -R ${SNAPSHOT_DIR}/$directory
+	    if [ $? -ne 0 ]; then
+		fuser -v ${SNAPSHOT_DIR}/$directory >> ${LOGFILE}
+		lsof ${SNAPSHOT_DIR}/$directory >> ${LOGFILE}
+		log_error "ERROR: second attempt to umount $directory also failed!"
+		EXITCODE=1;
+	    else
+		log_info "Second attempt to umount $directory succeeded."
+	    fi
 	fi
     done
 
