Enable automatic migration of /etc contents (copy)
Copy the contents of the existing /etc overlay file system into the
snapshot; this will enable RPM scripts which are trying to modify
existing configuration files to be able to do so now (up until now
they just didn't see the files in the overlay).
On first boot after a new snapshot generation delete the contents of
the overlay to avoid inconsistencies with older snapshots. This will
loose all changes to /etc since the last snapshot though, and old
snapshots will get the changes accumulated since the last snapshot.

diff --git a/sbin/transactional-update.in b/sbin/transactional-update.in
--- a/sbin/transactional-update.in
+++ b/sbin/transactional-update.in
@@ -722,6 +722,14 @@ if [ -n "${ZYPPER_ARG}" -o ${REWRITE_GRUB_CFG} -eq 1 \
 	fi
     done
 
+    # Copy the contents of /etc
+    log_info "Copying /etc state into snapshot"
+    rsync --archive --quiet --exclude '/etc/transactional-update.newsnapshot' --delete-excluded /etc ${SNAPSHOT_DIR}
+    if [ $? -ne 0 ]; then
+	log_error "ERROR: copying of /etc into snapshot failed!"
+	quit 1;
+    fi
+
     # If we have a seperate /var, create some directories which we
     # will delete again later.
     if [ ${HAS_SEPARATE_VAR} -eq 1 ]; then
@@ -893,6 +901,8 @@ if [ -n "${ZYPPER_ARG}" -o ${REWRITE_GRUB_CFG} -eq 1 \
 		# Save the old snapshot or else it will get lost.
 		add_unique_id ${CURRENT_SNAPSHOT_ID}
 		save_state_file ${SNAPSHOT_ID}
+		# Mark /etc contents as deleteable
+		touch /etc/transactional-update.newsnapshot
 		# Reset in-progress flag
 		snapper ${SNAPPER_NO_DBUS} modify -u "transactional-update-in-progress=" ${SNAPSHOT_ID}
 	    fi
