Add cleanup algorithm for old overlays

diff --git a/sbin/transactional-update.in b/sbin/transactional-update.in
--- a/sbin/transactional-update.in
+++ b/sbin/transactional-update.in
@@ -802,6 +802,14 @@ if [ ${DO_CLEANUP} -eq 1 ]; then
 	UNUSED_SNAPSHOTS="${_new_unused}"
 	save_state_file 0
     fi
+
+    # Clean up old unused overlays
+    for overlay in /var/lib/overlay/[0-9]*; do
+	if ! grep -q "${overlay}/etc" /.snapshots/*/snapshot/etc/fstab.sys; then
+	    log_info "Deleting unused overlay ${overlay}"
+	    rm -rf "${overlay}"
+	fi
+    done
 fi
 
 if [ -n "${ZYPPER_ARG}" -o ${REWRITE_GRUB_CFG} -eq 1 \
