Revert "t-u: Remove "kdump" command"
The kdump command is still required to trigger S/390's fadump

This reverts commit 9a1f2aded48829e10a29cba201bf576ba393d3cd.

diff --git a/sbin/transactional-update.in b/sbin/transactional-update.in
--- a/sbin/transactional-update.in
+++ b/sbin/transactional-update.in
@@ -18,6 +18,7 @@ REWRITE_BOOTLOADER=0
 REWRITE_GRUB_CFG=0
 REWRITE_GRUB_CFG_NO_REBOOT=0
 REWRITE_INITRD=0
+REBUILD_KDUMP_INITRD=0
 DO_APPLY=0
 DO_APPLY_OCI=0
 DO_CLEANUP_OVERLAYS=0
@@ -150,6 +151,7 @@ usage() {
     echo "grub.cfg                   Regenerate grub.cfg"
     echo "bootloader                 Reinstall the bootloader"
     echo "initrd                     Regenerate initrd"
+    echo "kdump                      Regenerate kdump initrd"
     echo "shell                      Open rw shell in new snapshot before exiting"
     echo "reboot                     Reboot after update"
     echo "run <cmd>                  Run a command in a new snapshot"
@@ -173,9 +175,6 @@ usage() {
     echo "Standalone Commands:"
     echo "rollback [<number>]        Set the current or given snapshot as default snapshot"
     echo "rollback last              Set the last working snapshot as default snapshot"
-    echo ""
-    echo "Deprecated Commands (will be ignored):"
-    echo "kdump"
     echo ""
     echo "Options:"
     echo "--interactive, -i          Use interactive mode for package command"
@@ -313,6 +312,17 @@ is_bls() {
         IS_BLS=$?
     fi
     return ${IS_BLS}
+}
+
+rebuild_kdump_initrd() {
+    if tukit ${TUKIT_OPTS} --quiet call "$1" systemctl is-enabled --quiet kdump.service; then
+        tukit ${TUKIT_OPTS} call "$1" /sbin/mkdumprd | log_info -o
+        return "${PIPESTATUS[0]}"
+    elif [ ${SETUP_KDUMP} -ge 1 ]; then
+        log_info "INFO: Requested rebuild of kdump initrd, but kdump is not enabled."
+        log_info "      Did you mean 'setup-kdump'?"
+    fi
+    return 0;
 }
 
 # Only called in error case; reverts everything to previous state.
@@ -632,10 +642,12 @@ parse_args() {
                 ;;
             initrd)
                 REWRITE_INITRD=1
+                REBUILD_KDUMP_INITRD=1
                 shift
                 ;;
             kdump)
-                # Deprecated
+                REBUILD_KDUMP_INITRD=1
+                SETUP_KDUMP=2
                 shift
                 ;;
             reboot)
@@ -751,6 +763,7 @@ parse_args() {
                 DO_APPLY_OCI=1
                 REWRITE_GRUB_CFG=1
                 REWRITE_INITRD=1
+                REBUILD_KDUMP_INITRD=1
                 shift
 
                 if [ $# -eq 0 ]; then
@@ -821,6 +834,8 @@ if [ "${SETUP_FIPS}" -eq 1 ]; then
     if [ ${#ZYPPER_ARG_EXTRA[@]} -ne 0 ]; then
         ZYPPER_ARG="install"
     fi
+    REWRITE_INITRD=1
+    REBUILD_KDUMP_INITRD=1
 fi
 
 # Setup SELinux
@@ -843,6 +858,7 @@ if [ "${SETUP_SELINUX}" -eq 1 ]; then
         ZYPPER_ARG="install"
     fi
     REWRITE_INITRD=1
+    REBUILD_KDUMP_INITRD=1
 
     # Make sure /var/lib/selinux exists, else installing the
     # Policy will fail
@@ -861,6 +877,7 @@ if [ ${SETUP_KDUMP} -eq 1 ]; then
     if [ ${#ZYPPER_ARG_EXTRA[@]} -ne 0 ]; then
         ZYPPER_ARG="install"
     fi
+    REBUILD_KDUMP_INITRD=1
 fi
 
 # If no commands were given, use default from config
@@ -1121,7 +1138,7 @@ if [ ${DO_CLEANUP_OVERLAYS} -eq 1 ]; then
 fi
 
 if [ -n "${ZYPPER_ARG}" ] || [ ${REWRITE_GRUB_CFG} -eq 1 ] \
-    || [ ${REWRITE_INITRD} -eq 1 ] \
+    || [ ${REWRITE_INITRD} -eq 1 ] || [ ${REBUILD_KDUMP_INITRD} -eq 1 ] \
     || [ ${RUN_SHELL} -eq 1 ] || [ ${DO_RUN} -eq 1 ] \
     || [ ${REWRITE_BOOTLOADER} -eq 1 ] || [ ${DO_REGISTRATION} -eq 1 ] \
     || [ ${DO_APPLY_OCI} -eq 1 ]; then
@@ -1251,6 +1268,7 @@ if [ -n "${ZYPPER_ARG}" ] || [ ${REWRITE_GRUB_CFG} -eq 1 ] \
         fi
 
         if [ "${RETVAL}" -eq 0 ] || [ "${RETVAL}" -eq 102 ] || [ "${RETVAL}" -eq 103 ] || { [ "${DO_DUP}" -eq 0 ] && [ "${RETVAL}" -eq 106 ]; } then
+            REBUILD_KDUMP_INITRD=1
             # check if products are updated and we need to re-register
             # at next boot.
             if ! diff -qr /etc/products.d "${SNAPSHOT_DIR}/etc/products.d" > /dev/null; then
@@ -1342,8 +1360,24 @@ if [ -n "${ZYPPER_ARG}" ] || [ ${REWRITE_GRUB_CFG} -eq 1 ] \
         elif ! is_bls && ! tukit ${TUKIT_OPTS} call "${SNAPSHOT_ID}" dracut ${DRACUT_OPTS} --force --regenerate-all | log_info -o; then
             log_error "ERROR: initrd creation failed!"
             EXITCODE=1
+        else
+            REBUILD_KDUMP_INITRD=1
         fi
         set_reboot_level "kexec"
+    fi
+
+    # mkinitrd depends on pbl, so it will fail (bsc#1226676)
+    if is_bls && [ ${REBUILD_KDUMP_INITRD} -eq 1 ]; then
+        log_info "WARNING: mkdumprd fails for this bootloader"
+        REBUILD_KDUMP_INITRD=0
+    fi
+    if [ ${REBUILD_KDUMP_INITRD} -eq 1 ]; then
+        log_info "Trying to rebuild kdump initrd"
+        if ! rebuild_kdump_initrd "${SNAPSHOT_ID}"; then
+            log_error "ERROR: kdump initrd creation failed!"
+            EXITCODE=1
+        fi
+        set_reboot_level "soft-reboot"
     fi
 
     if is_bls && { [ ${REWRITE_GRUB_CFG} = 1 ] || [ ${REWRITE_GRUB_CFG_NO_REBOOT} = 1 ]; }; then
