Fix path for temporary files Fix usage output for PTFs Implement lock file

diff --git a/sbin/transactional-update.in b/sbin/transactional-update.in
--- a/sbin/transactional-update.in
+++ b/sbin/transactional-update.in
@@ -2,7 +2,8 @@
 #
 # update_snapshot - update a snapshot of the current system
 #
-# Copyright (C) 2016 by Thorsten Kukuk <kukuk@suse.com>
+# Author: Thorsten Kukuk <kukuk@suse.com>
+# Copyright (C) 2016 SUSE Linux GmbH
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -37,7 +38,7 @@ SECOND_SNAPSHOT_ID=""
 usage() {
     echo "Usage: transactional-update --help|--version"
     echo "       transactional-update [cleanup][up|dup|patch|bootloader][reboot]"
-    echo "       transactional-update [cleanup] ptr install|remove [reboot]"
+    echo "       transactional-update [cleanup] [reboot] ptf install|remove PKG1..PKGN"
     exit $1
 }
 
@@ -54,6 +55,34 @@ log_error() {
     echo `date "+%Y-%m-%d %H:%M "` "$@" >> ${LOGFILE}
     echo "$@" 1>&2
 }
+
+function bashlock {
+     if [ "$#" -ne 1 ]; then
+        echo 'usage: bashlock [LOCKFILENAME]' 1>&2
+        return 2
+     fi
+     LOCKFILE="$1"
+
+     echo "$$" >"$LOCKFILE.$$"
+     if ! ln "$LOCKFILE.$$" "$LOCKFILE" 2>/dev/null; then
+        PID=`head -1 "$LOCKFILE"`
+        if [ -z "$PID" ]; then
+           rm -f "$LOCKFILE"
+        else
+           kill -0 "$PID" 2>/dev/null || rm -f "$LOCKFILE"
+        fi
+
+        if ! ln "$LOCKFILE.$$" "$LOCKFILE" 2>/dev/null; then
+           rm -f "$LOCKFILE.$$"
+           return 1
+        fi
+     fi
+
+     rm -f "$LOCKFILE.$$"
+     trap 'rm -f "$LOCKFILE"' EXIT
+
+     return 0
+  }
 
 save_state_file() {
     LOCAL_STATE_FILE=${STATE_FILE}
@@ -83,6 +112,12 @@ quit() {
 }
 
 ORIG_ARGS="$@"
+
+bashlock "/var/run/transactional-update.pid"
+if [ $? - ne 0 ]; then
+  echo "Couldn't get lock, another instance is already running?"
+  exit 1;
+fi
 
 # load old state file
 if [ -f ${STATE_FILE} ]; then
@@ -240,7 +275,7 @@ fi
 if [ -n "${ZYPPER_ARG}" -o ${REWRITE_BOOTLOADER} -eq 1 -o ${REWRITE_GRUB_CFG} -eq 1 ]; then
 
     #check if there are updates at all
-    TMPFILE=`mktemp transactional-update.XXXXXXXXXX`
+    TMPFILE=`/tmp/mktemp transactional-update.XXXXXXXXXX`
     zypper --xml ${ZYPPER_NONINTERACTIVE} ${ZYPPER_ARG} --dry-run ${ZYPPER_ARG_PKGS} > ${TMPFILE}
     if [ $? -ne 0 ]; then
 	log_error "ERROR: zypper failed!"
