Only sync /etc if it's on an overlayfs mount

diff --git a/sbin/transactional-update.in b/sbin/transactional-update.in
--- a/sbin/transactional-update.in
+++ b/sbin/transactional-update.in
@@ -300,6 +300,18 @@ check_registration_on_next_reboot() {
     fi
 }
 
+# Sync /etc mount contents to target directory
+sync_etc() {
+    if findmnt -t overlay /etc >/dev/null; then
+	log_info "Copying /etc state into snapshot $1"
+	rsync --archive --xattrs --acls --quiet /etc "$1"
+	if [ $? -ne 0 ]; then
+	    log_error "ERROR: copying of /etc into snapshot $1 failed!"
+	    quit 1
+	fi
+    fi
+}
+
 ORIG_ARGS=("$@")
 
 # If no option is given, assume "up"
@@ -681,12 +693,7 @@ if [ -n "${ZYPPER_ARG}" -o ${REWRITE_GRUB_CFG} -eq 1 \
     fi
 
     # Copy the contents of /etc into the backup snapshot
-    log_info "Copying /etc state into backup snapshot"
-    rsync --archive --xattrs --acls --quiet /etc ${BACKUP_SNAPSHOT_DIR}
-    if [ $? -ne 0 ]; then
-	log_error "ERROR: copying of /etc into backup snapshot failed!"
-	quit 1
-    fi
+    sync_etc ${BACKUP_SNAPSHOT_DIR}
 
     # Create the working snapshot
     SNAPSHOT_ID=`snapper create --type post --pre-number ${BACKUP_SNAPSHOT_ID} -p -u "transactional-update-in-progress=yes" -d "Snapshot Update"`
@@ -775,13 +782,8 @@ if [ -n "${ZYPPER_ARG}" -o ${REWRITE_GRUB_CFG} -eq 1 \
 	fi
     done
 
-    # Copy the contents of /etc
-    log_info "Copying /etc state into snapshot"
-    rsync --archive --xattrs --acls --quiet /etc ${SNAPSHOT_DIR}
-    if [ $? -ne 0 ]; then
-	log_error "ERROR: copying of /etc into snapshot failed!"
-	quit 1
-    fi
+    # Copy the contents of /etc into snapshot
+    sync_etc ${SNAPSHOT_DIR}
 
     # If we have a seperate /var, create some files / directories which we
     # will delete again later.
