Re-add rollback snapshots to managed list
Previously, when a snapshot had been assigned a cleanup algorithm already
(triggered by a `cleanup` run), and then a rollback to that snapshot would be
performed, then the cleanup algorithm would be emptied again, but the snapshot
would not be added back to the list of managed snapshots - so the snapshot
would never be deleted automatically.

diff --git a/sbin/transactional-update.in b/sbin/transactional-update.in
--- a/sbin/transactional-update.in
+++ b/sbin/transactional-update.in
@@ -1196,8 +1196,12 @@ if [ ${DO_ROLLBACK} -eq 1 ]; then
 	    # reboot.
 	    check_registration_on_next_reboot
 	fi
-	# Remove possible cleanup algo
-        snapper modify -c '' ${ROLLBACK_SNAPSHOT}
+	# Remove possible cleanup algo and re-add to list
+	if ! \( echo "${LAST_WORKING_SNAPSHOTS} ${UNUSED_SNAPSHOTS}" | grep --word-regexp --quiet "${ROLLBACK_SNAPSHOT}" \); then
+	    UNUSED_SNAPSHOTS="${UNUSED_SNAPSHOTS} ${ROLLBACK_SNAPSHOT}"
+	    save_state_file 0
+	fi
+	snapper modify -c '' ${ROLLBACK_SNAPSHOT}
 
 	if [ ${NEED_REBOOT_WARNING} -eq 0 ]; then
 	    rm -f "${NEEDS_RESTARTING_FILE}"
