Fix duplicate overlay mount during migration
When migrating a system from overlayfs based /etc to btrfs subvolume based
/etc the overlayfs directories were reused. This can result in strange
errors such as "Permission denied" or "File not found" in the running
system because the workdir was not consistent any more.

This commit creates separate directories now.
It also covers a few more cases which may actually happen:
* If the snapshot is based on the current, not yet migrated system, then
use /etc directly. This is officially supported by the kernel because
reusing an upperdir directly isn't.
* Same for several overlay stacks: If the current system is part of the
overlayfs stack, then just use the mounted /etc directly.
* If the migration to btrfs subvolumes was done, but the system was not
rebooted yet and a --continue on the new snapshot is performed, the plugin
cannot create a snapshot of the current /etc because that one is not
migrated yet. Add back some overlayfs support to sync the files correctly.
* Edge case: When using the snapper plugin on an old snapshot which doesn't
contain it, then abort: That system could not be upgraded any more because
it's missing the required subvolume handling components.

Fixes [bsc#1272529].

diff --git a/snapper/50-etc b/snapper/50-etc
--- a/snapper/50-etc
+++ b/snapper/50-etc
@@ -20,14 +20,19 @@ create_reference_etc() {
     rmdir "/.snapshots/${snapshot}/snapshot/etc/etc.syncpoint"
   fi
   # Syncing is only necessary when the snapshot is based on the currently running system.
-  # "Current" means the snapshot number of the currently running /usr
-  current="$(findmnt --target /usr --raw --noheadings --output FSROOT | tail -n 1 | cut -d '/' -f 4)"
 
   # If the parent snapshot was created from the running system, perform a sync now and use the current running /etc as syncpoint
   if [ -e "/.snapshots/${parent}/snapshot/etc/etc.syncpoint/transactional-update.comparewith" ] \
      && [ "$(cat "/.snapshots/${parent}/snapshot/etc/etc.syncpoint/transactional-update.comparewith")" = "${current}" ]; then
     # Snapshot first, then sync to avoid racing with changes to /etc in between.
-    btrfs subvolume snapshot "/etc" "/.snapshots/${snapshot}/snapshot/etc/etc.syncpoint"
+    if btrfs subvolume list / | grep -Eq " path (@/.snapshots/${current}/snapshot/)?etc"; then
+      btrfs subvolume snapshot "/etc" "/.snapshots/${snapshot}/snapshot/etc/etc.syncpoint"
+    else
+      # Old overlay systems still have to be supported because after first boot config management software may use --continue after a migration and before the reboot
+      btrfs subvolume create "/.snapshots/${snapshot}/snapshot/etc/etc.syncpoint"
+      rsync --quiet --archive --xattrs --acls "/etc/" "/.snapshots/${snapshot}/snapshot/etc/etc.syncpoint"
+    fi
+
     /usr/libexec/transactional-update-sync-etc-state --keep-syncpoint "/.snapshots/${snapshot}/snapshot/etc/etc.syncpoint" "/.snapshots/${snapshot}/snapshot/etc" "/.snapshots/${parent}/snapshot/etc/etc.syncpoint"
     echo "${current}" > "/.snapshots/${snapshot}/snapshot/etc/etc.syncpoint/transactional-update.comparewith"
   # If it's the first descendant of the current system store a reference copy of the state before changes will be applied ...
@@ -51,6 +56,17 @@ create_snapshot_post() {
   parent="$(btrfs subvolume list -u / | grep " uuid ${parentuuid} " | cut -f 9- -d ' ' | cut -f 3 -d '/')"
   # "Parent ID" means the parent subvolume in the file system tree
   parentid="$(btrfs subvolume list / | grep -E " path @/.snapshots/${parent}/snapshot"$ | cut -f 2 -d ' ')"
+  # "Current" means the snapshot number of the currently running /usr
+  current=$(findmnt --target /usr --raw --noheadings --output FSROOT --first-only --direction backward --types btrfs | sed -e 's|.*.snapshots/\(.*\)/snapshot.*|\1|g')
+  if [ -z "${current}" ]; then
+    current=$(findmnt --target / --raw --noheadings --output FSROOT --first-only --direction backward --types btrfs | sed -e 's|.*.snapshots/\(.*\)/snapshot.*|\1|g')
+  fi
+
+  # Abort if base snapshot has plugin, otherwise it would create a snapshot with the new mechanism which cannot be updated any more by an old t-u version.
+  if [ ! -e "/.snapshots/${parent}/snapshot/${0}" ]; then
+    echo "System in base snapshot does not support /etc subvolumes - aborting!"
+    exit 2
+  fi
 
   make_sure_snapshot_is_writable
 
@@ -64,12 +80,21 @@ create_snapshot_post() {
     btrfs subvolume create "/.snapshots/${snapshot}/snapshot/etc"
 
     # Syncing old /etc state
-    oldetcopts="$(findmnt --output OPTIONS --noheadings --fstab --tab-file "/.snapshots/${parent}/snapshot/etc/fstab" /etc | sed 's;/sysroot/;/;g')"
-    mkdir "/var/lib/overlay/${parent}/rsync"
-    trap 'rmdir "/var/lib/overlay/${parent}/rsync"' EXIT
-    mount -t overlay overlay -o"${oldetcopts}" "/var/lib/overlay/${parent}/rsync"
-    trap 'umount "/var/lib/overlay/${parent}/rsync" && rmdir "/var/lib/overlay/${parent}/rsync"' EXIT
-    rsync --quiet --archive --xattrs --acls "/var/lib/overlay/${parent}/rsync/" "/.snapshots/${snapshot}/snapshot/etc"
+    if [ "${parent}" -eq "${current}" ]; then
+      rsyncsource="/etc/"
+    else
+      rsyncsource="/var/lib/overlay/${parent}/rsync/"
+      oldetcopts="$(findmnt --output OPTIONS --noheadings --fstab --tab-file "/.snapshots/${parent}/snapshot/etc/fstab" /etc | sed 's;/sysroot/;/;g')"
+      # Mount everything as readonly, i.e. lowerdirs
+      etcopts="$(echo ${oldetcopts} | gawk '{ match($0,/upperdir=([^,[:space:]]+)/,upper); match($0,/lowerdir=([^,[:space:]]+)/,lower); print "lowerdir=" upper[1] ":" lower[1] }')"
+      # If the current system is part of the stack remove it and all lower layers and use it directly instead
+      etcopts="$(echo ${oldetcopts} | sed "s;/var/lib/overlay/${current}/etc.*;/etc;")"
+      mkdir -p "${rsyncsource}"
+      mount -t overlay overlay -o"${etcopts}" "${rsyncsource}"
+      trap 'umount "/var/lib/overlay/${parent}/rsync"' EXIT
+    fi
+
+    rsync --quiet --archive --xattrs --acls "${rsyncsource}" "/.snapshots/${snapshot}/snapshot/etc"
 
     create_reference_etc
 
